docs_dir: "src"
site_name: "Chomping at the Bit"
site_url: "https://www.ourchitecture.io/chomping-at-the-bit/"
repo_url: "https://github.com/ourchitecture/chomping-at-the-bit/#readme"
repo_name: ourchitecture/chomping-at-the-bit
edit_uri: "edit/main/projects/docs/src"
site_author: "Ourchitecture"
copyright: "Creative Commons Zero v1.0 Universal"
theme:
  name: "material"
  custom_dir: "./mkdocs/overrides"
  logo: "assets/icons/chomping-at-the-bit.png"
  favicon: "assets/icons/chomping-at-the-bit.png"
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: "slate"
      primary: "blue"
      accent: "deep orange"
      toggle:
        icon: "material/weather-sunny"
        name: "Switch to light mode"
    - scheme: "default"
      primary: "blue grey"
      accent: "light blue"
      toggle:
        icon: "material/weather-night"
        name: "Switch to dark mode"
  features:
    - "header.autohide"
    - "navigation.indexes"
    - "navigation.tabs"
    - "navigation.tabs.sticky"
    - "navigation.top"
    - "navigation.sections"
    - "toc.integrate"
nav:
  - "Digital Value Delivery": "index.md"
  - "Resources": "value-delivery-resources.md"
  - "Structures": "value-delivery-structures.md"
  - "Lifecycle": "value-delivery-lifecycle.md"
  - "Concerns": "value-delivery-concerns.md"
  - "Blog": "blog.md"
  - "License": "license.md"
extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/ourchitecture/chomping-at-the-bit/"
      name: "GitHub"
  generator: false
markdown_extensions:
  - "admonition"
  - "attr_list"
  - "def_list"
  - "md_in_html"
  - "meta"
  - "pymdownx.details"
  - "pymdownx.emoji":
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - "pymdownx.highlight"
  - "pymdownx.inlinehilite"
  - "pymdownx.keys"
  - "pymdownx.magiclink"
  - "pymdownx.snippets"
  - "pymdownx.superfences":
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - "pymdownx.tasklist":
      custom_checkbox: true
  - "tables"
