name: gh-docs

on:
  push:
    branches: [main]
    paths:
      - "makefile"
      - "mkdocs.yml"
      - ".github/workflows/gh-docs.yaml"
      - "projects/webapp/**"

jobs:
  generate:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      # create a release
      # navigate to project root
      # commit release files back to source control
      - name: documentation
        working-directory: ./projects/webapp/
        run: |
          chmod +x ./release.sh
          make release
          cd ../../
          git config user.name our-github-actions
          git config user.email ericis@users.noreply.github.com
          git add .
          git commit -m 'docs: auto-generate documentation [skip ci]'
          git push
